server:
  port: 9007
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/Warehouse
    username: root
    password: JY@class4579
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true


